### ISSUE TITLE
Thunderbolt 3 - NVM 23

### ISSUE THREAD

**Issue by pierpaolodimarzo** [pierpaolodimarzo/ThinkPad-T480#9]
1. BIOS assist mode was disabled (original default setting)

2. Go to Lenovo and download:
**Intel Thunderbolt Software (Version 17.x = n22ta14w.exe = latest) 
Thunderbolt Firmware Update Utility (n24th13w.exe = latest) 
Lenovo Power Management Driver (n3aku12w.exe = 1.68.30.0 i.e. an older version)**

3. Turn on Flight mode to prevent Windows updating drivers

4. Uninstall Thunderbolt Software or Control Centre and go to Device Manager and uninstall Thunderbolt(TM) Controller

5. Whilst in Device Manager uninstall Lenovo PM Device

6. Restart

7. Install **n22ta14w.exe** and **n3aku12w.exe**

8. **Restart**

9. Go into Device Manager and check that Thunderbolt(TM) 17.4.80.94 and Lenovo PM Device 1.68.30.0. 
You can also check Thunderbolt version in the Sys Tray Thunderbolt Software (Right click) -> about

10. Plug in charger to laptop, I used the non-Thunderbolt USB-C port due to the installation instructions on the next step

11. Install **n24th13w.exe** which will take you through an installer (which I hadn't seen until using the older Lenovo PM Device driver). It will say something along the lines of not plugging anything into Thunderbolt

12. Finish the installer and restart

13. Check Lenovo Software in Sys Tray; **NVM version 23.0**

14. Now turn on Wi-Fi

[Thunderbolt_Update.zip](https://github.com/pierpaolodimarzo/ThinkPad-T480/files/11185818/Thunderbolt_Update.zip)

**Comment by dinels12** [comment]
Can you please leave a tutorial of dual boot win11/Ventura? please

**Comment by vigilancer** [comment]
Your instructions did't work for me (couldn't update NVMe firmware 20 -> 23).
Instructions from this reddit post helped: https://www.reddit.com/r/thinkpad/comments/ew400w/t480_thunderbolt_issue_solved/

**Comment by widiu7omo** [comment]
It's working if you follow the instruction carefully. Mine T480 i5-8350U

**Comment by me-when-the-uh** [comment]
I managed to install it properly on the second try, as the PM Device apparently refused to be uninstalled+removed. It showed ver. 1.68.37.0, which is the newest version and not the one that works. After trying it again on the second try, I noticed that the PM Device driver had become 1.68.30.0, and that was before I was going to install the PM Device driver, so I moved on to other steps because the requirement has already been met.

I dodged the bullet somehow because to this day the Thunderbolt version was 14.0 on my T480 that I got last week. It worked well, but I had problems with connecting my second external monitor, whether I connected the first or the second one via HDMI or USB-C. Somehow it all started working fine after trying the Thunderbolt port yet again.

**Comment by fpolguti** [comment]
Sorry for opening this again, I'm doing all those steps on a T490.
I'm stuck here
Go into Device Manager and check that Thunderbolt(TM) 17.4.80.94 and Lenovo PM Device 1.68.30.0.
You can also check Thunderbolt version in the Sys Tray Thunderbolt Software (Right click) -> about

I can see Lenovo PM Device but I can't see the driver Thunderbolt(TM) so when I try to install the firmware later I'm getting this error: 0x227 SDK_NO_DRIVER Thunderbolt DCH software is not installed

Thanks for any suggestion.

**Comment by okbrown** [comment]
So there is no process one can follow, if you already have macOS installed?

**Comment by thishome** [comment]
> I can see Lenovo PM Device but I can't see the driver Thunderbolt(TM) so when I try to install the firmware later I'm getting this error: 0x227 SDK_NO_DRIVER Thunderbolt DCH software is not installed

Hi, have you solved the problem? me with the same problem in device manager, I can't see Thunderbolt(TM) either, so i'm not sure what to do next...

**Comment by thishome** [comment]
> So there is no process one can follow, if you already have macOS installed?

Seems so

**Comment by cchewanik** [comment]
> > I can see Lenovo PM Device but I can't see the driver Thunderbolt(TM) so when I try to install the firmware later I'm getting this error: 0x227 SDK_NO_DRIVER Thunderbolt DCH software is not installed
> 
> Hi, have you solved the problem? me with the same problem in device manager, I can't see Thunderbolt(TM) either, so i'm not sure what to do next...

Hi, when following the instructions I didn't have Thunderbolt(TM) originally either, but I followed the remainder of the instructions and it worked (just did it recently on a T480 with latest version of Windows)

**Comment by fpolguti** [comment]
Hi, I ended up calling Lenovo support, they sent me the Lenovo Image for W10 for the T490, I installed and sent them the some logs. They said it was a motherboard issue and since it is out of warranty they could replace the motherboard at a cost of 1700 Euros, brilliant...

**Comment by mphysic** [comment]
Bro! I Love YOU!!!! Thanks a lot. I've spent several hours trying update firmware before found this instruction!
It works ONLY with that versions you provide. Not older, not newer.
Thank You!

**Comment by thishome** [comment]
> > I can see Lenovo PM Device but I can't see the driver Thunderbolt(TM) so when I try to install the firmware later I'm getting this error: 0x227 SDK_NO_DRIVER Thunderbolt DCH software is not installed
> 
> Hi, have you solved the problem? me with the same problem in device manager, I can't see Thunderbolt(TM) either, so i'm not sure what to do next...

me also ok,  I end up reinstall the whole OS, and do it again, everything is just as expected.

**Comment by sayantangr** [comment]
Thanks for the tutorial.

**Comment by tryfail** [comment]
The guide in your post saved me in 20250809 on a standard T480 using multiple docks (usb c gen 2 and the "slice" one). A couple of notes:

1. there is no information of where to get the old PM driver version. Here is a link https://download.lenovo.com/pccbbs/mobiles/n3aku12w.exe
2. symptoms: all docks stopped working (monitors not working, some USB not working) except for charging and network cable RJ45 port. HDMI on the laptop port still worked if dock was disconnected
3. before doing this procedure there was a "Thunderbolt" line in Device Manager > System Device
4. after this procedure, everything appears to be working on the slide dock. The USB C gen 2 dock does not work for video output. Also that "Thunderbolt" line in Device Manager is gone and I am not sure what to do to get it back. Maybe because of this, the app Thunderbolt Software on Windows 11 show no output
5. after everything is working, I ran Lenovo Vantage and it upgraded Lenovo PM to 1.69.X and after multiple reboots everything that was working still works

Not going to worry too much about the USB ports. All I really needed was the extra screens on the slice dock
